# Generated by Django 3.2.4 on 2021-06-18 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.sftpstorage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('jmbg', models.CharField(max_length=13, unique=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
            ],
            options={
                'verbose_name_plural': 'Children',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HangOutTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('mood', models.CharField(choices=[('good', '😁'), ('ok', '🙂'), ('bad', '😔')], default='ok', max_length=10)),
                ('text', models.TextField(blank=True)),
                ('completed', models.BooleanField()),
                ('photo', models.ImageField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='photos')),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.child')),
                ('created_by', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.department')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.hangouttheme')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.department'),
        ),
    ]
