# Generated by Django 2.2.7 on 2020-10-06 09:20

from django.db import migrations
from django.contrib.auth import get_user_model

def create_user(apps, schema_editor):
    User = get_user_model()
    User.objects.create_superuser(password='admin', email='admin@admin.com')

class Migration(migrations.Migration):

    dependencies = [
        ('prevencija', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user),
    ]



